[build]
  publish = ".next"
  command = "yarn build"

[[redirects]]
  from = "/blog/category/*"
  to = "/blog/tag/:splat"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"