name: Update Post Content
on:
  pull_request:
    paths: ["content/**"]
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'update-content')
    name: Update and deploy content
    runs-on: ubuntu-latest
    steps:
      - name: Fetch all tags
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout to latest tags
        run: git checkout $(git describe --tags $(git rev-list --tags --max-count=1))

      - name: Get latest change in content directory from master branch
        run: git checkout master content/

      - name: Setup build env
        run: echo ${{ secrets.BUILD_ENV }} > .env

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"

      - name: Install netlify cli
        run: yarn global add netlify-cli

      - name: Install dependencies
        run: yarn

      - name: Build app
        run: yarn build

      - name: Deploy to netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod --dir=public

      - name: Remove build env
        run: rm .env
