name: Lint and Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint and Test all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Run linter script
        run: yarn lint

      - name: Run type check script
        run: yarn type-check

      - name: Run test script
        run: yarn test
