name: Deploy and Release
on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Build and deploy website
    runs-on: ubuntu-24.04
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
      GH_REPO: ${{ secrets.GH_REPO }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      CONTENT_DIR: ${{ secrets.CONTENT_DIR }}
      SITE_URL: ${{ secrets.SITE_URL }}
    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Cache netlify
        uses: actions/cache@v4
        with:
          path: ./.netlify
          key: ${{ runner.os }}-netlify-${{ hashFiles('**/netlify.toml') }}
          restore-keys: |
            ${{ runner.os }}-netlify-

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "yarn"

      - name: Install netlify cli
        run: yarn global --ignore-optional add netlify-cli

      - name: Install dependencies
        run: yarn

      - name: Build and Deploy to netlify
        run: netlify deploy --prod --build --context production

  release:
    needs: deploy
    name: Create release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Release tag
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
