name: Deploy and Release
on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Build and deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Setup build env
        run: echo ${{ secrets.BUILD_ENV }} > .env

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"

      - name: Install netlify cli
        run: yarn global add netlify-cli

      - name: Install dependencies
        run: yarn

      - name: Build app
        run: yarn build

      - name: Deploy to netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod --dir=public

      - name: Remove build env
        run: rm .env

  release:
    needs: deploy
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Release tag
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
