name: Deploy and Release
on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Build and deploy website
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Cache netlify
        uses: actions/cache@v3
        with:
          path: ./.netlify
          key: ${{ runner.os }}-netlify-${{ hashFiles('**/netlify.toml') }}
          restore-keys: |
            ${{ runner.os }}-netlify-

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"

      - name: Install netlify cli
        run: yarn global add netlify-cli

      - name: Install dependencies
        run: yarn

      - name: Build app
        run: netlify build

      - name: Deploy to netlify
        run: netlify deploy --prod

  release:
    needs: deploy
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Release tag
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
