name: Deploy and Release
on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Build and deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master
          submodules: recursive

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"

      - name: Install netlify cli
        run: yarn global add netlify-cli

      - name: Install dependencies
        run: yarn

      - name: Build app
        run: yarn build

      - name: Deploy to netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod --dir=public

  release:
    needs: deploy
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Get Tag
        id: get-tag
        run: echo "::set-output name=tag::$(echo ${{ github.ref }} | cut -d '/' -f3)"

      - name: Release tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: "Please visit <https://gagahpangeran.com>! You can also check [changelog of this release](https://gagahpangeran.com/changelog/${{ steps.get-tag.outputs.tag }})."
